<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
	<TargetFramework>net8.0</TargetFramework>
	<LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\KNet.Common\KNet.Common.csproj" />
    <ProjectReference Include="..\..\KNet.Extentions.Protobuf\KNet.Extentions.Protobuf.csproj" />
  </ItemGroup>

</Project>
