<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>KNet.WebSocket.Server.WebSocketSharp</AssemblyName>
    <RootNamespace>KNet.WebSocket.Server.WebSocketSharp</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <!-- 官方稳定版对 net8 无 netstandard 支持，故用带 netstandard2.0 的预发布 1.0.3-rc9 -->
    <PackageReference Include="WebSocketSharp" Version="1.0.3-rc9" />
    <ProjectReference Include="..\..\KNet.Common\KNet.Common.csproj" />
  </ItemGroup>

</Project>
