<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
	<TargetFrameworks>netstandard2.1;net8.0</TargetFrameworks>
	<LangVersion>latest</LangVersion>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\AKNet.Common\AKNet.Common.csproj" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="AKNet.WebSocket.jslib" />
  </ItemGroup>
</Project>
