<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\KNet.Common\KNet.Common.csproj" />
    <ProjectReference Include="..\KNet.MSQuic\KNet.MSQuic.csproj" />
  </ItemGroup>

</Project>
