<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
	  <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\KNet.Common\KNet.Common.csproj" />
    <ProjectReference Include="..\..\..\WebSocket\KNet.WebSocket.Server.HttpListener\KNet.WebSocket.Server.HttpListener.csproj" />
    <ProjectReference Include="..\..\TestCommon\TestCommon.csproj" />
  </ItemGroup>

</Project>
